postgres:
  url: ${POSTGRES_URL:localhost:5433}
  schema: ${POSTGRES_SCHEMA:auth-server-ms}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:123456}

redis:
  url: ${REDIS_URL:localhost}
  port: ${REDIS_PORT:6379}

server:
  undertow:
    threads:
      worker: 10
      io: 2

logging:
  level:
    com.kaua.ecommerce.auth.infrastructure: INFO

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration