codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 1%  # Fail if coverage decreases by more than 1%
        target: 95%    # Require at least 95% coverage
  ignore:
    - "infrastructure/src/main/java/com/kaua/ecommerce/auth/infrastructure/configurations/*"
    - "infrastructure/src/main/java/com/kaua/ecommerce/auth/infrastructure/Main.class"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false