version: '3.7'

services:
  postgres:
    container_name: ecommerce-auth-server-ms-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth-server-ms
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    networks:
      - ecommerce-auth-server-ms-network

networks:
  ecommerce-auth-server-ms-network:
    driver: bridge
  ecommerce-network:
    driver: bridge